config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  namespace :account do
    resource :password, only: %i[edit update]
  end

  resources :passwords, param: :token
  resources :posts
  resource  :profile, only: %i[show update]
  resource  :registration, only: %i[new create]
  resource  :session


  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  #-----------------------------------------------------------------------------
  # Associations
  #-----------------------------------------------------------------------------
  belongs_to :user
  belongs_to :organization
  has_rich_text :message

  #-----------------------------------------------------------------------------
  # Validations
  #-----------------------------------------------------------------------------
  validates :title, presence: true
  validates :message, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authorize_user!, only: %i[ edit update destroy ]

  # GET /posts
  def index
    @posts = current_organization.posts.order(created_at: :desc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Your post was successfully created."
    else
      flash.now[:alert] = "Your post could not be created. Please address any errors below."
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Your post was successfully updated.", status: :see_other
    else
      flash.now[:alert] = "Your post could not be updated. Please address any errors below."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, notice: "Your post was successfully deleted.", status: :see_other
  end

  private

    def set_post
      @post = Post.find(params.expect(:id))
    end

    def post_params
      params.expect(
        post: [ :title, :message, :user_id ]
      ).merge(
        user_id: current_user.id,
        organization_id: current_organization.id
      )
    end

    def authorize_user!
      return if @post.user == current_user

      redirect_to posts_path
    end
end

app/views/posts/edit.html.erb
<%= render Components::Posts::Form.new(post: @post, submit_text: "Update post", cancel_path: post_path(@post)) %>

app/views/posts/index.html.erb
<% content_for :title, [current_organization.name, "-", "Posts"].join(" ") %>

<div class="bg-white dark:bg-gray-800 px-4 md:px-16 py-4 md:py-16 rounded shadow-md mx-auto container relative">
  <%= render Components::Posts::Index.new(posts: @posts) %>
</div>
<%= render Components::Posts::NewButton.new %>

app/views/posts/new.html.erb
<%= render Components::Posts::Form.new(post: @post, submit_text: "Create post", cancel_path: posts_path) %>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>

<div class="container">
  <%= render Components::Breadcrumbs.new(breadcrumbs: [
    { title: "Posts", path: posts_path },
    { title: @post.title.truncate(30), path: post_path(@post) }
  ]) %>
<div class="bg-white dark:bg-gray-800 px-4 md:px-16 py-4 md:py-16 mt-10 md:mt-0 rounded shadow-md mx-auto container relative">
  <%= render Components::Posts::Show.new(post: @post) %>
</div>